spring:
  kafka:
    consumer:
      group-id: email
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
      bootstrap-servers: localhost:9092
    topic:
      name: order_topics
  application:
    name: email-service
server:
  port: 8080
